name: Deploy Jekyll site to Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby-full build-essential zlib1g-dev
        echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
        echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
        source ~/.bashrc

    - name: Install dependencies
      run: |
        gem install bundler
        bundle config set --local path 'vendor/bundle'
        bundle install

    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
